### ISSUE TITLE
Crash on reportSoftException when lineNumber is missing

### ISSUE THREAD

**Issue by yogeshchoudhary147** [errwischt/stacktrace-parser#10]
Android app crashes when ExceptionsManagerModule.reportSoftException is called with a stack trace that has frames without lineNumber.

The following fatal exception is logged.

`2019-04-09 16:14:29.742 7083-7781/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: co.armortext.messenger, PID: 7083
    com.facebook.react.bridge.NoSuchKeyException: lineNumber
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:124)
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:128)
        at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:182)
        at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)`

It started on 5th April when 0.1.5 was released.

I can confirm that downgrading it to 0.1.4, be specifying it in package.json, has resolved the issue for us.

**Comment by Calamari** [comment]
That looks like a Java stack trace. I never actively tested any stack traces except JavaScript so far. So there was no guarantee that it would work. But I can check it out and see what happens, but for that, it might be helpful to get the original stack trace, on which the parsers choke. Can you access it somehow?

**Comment by Calamari** [comment]
I just realized that this is an error happening within react bridge. Is it possible to get the original stack trace, that causes that exception, @yogeshchoudhary147?

**Comment by hfrosh** [comment]
@Calamari I believe this this bug was posted as a result of this issue reported for React Native: https://github.com/facebook/react-native/issues/24382

**Comment by dimlksin2** [comment]
com.facebook.react.bridge.NoSuchKeyException: lineNumber
	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:122)
	at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:158)
	at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:154)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:762)

**Comment by Calamari** [comment]
Since this seems not to be a bug in this library, rather in the usage within the Java react-bridge app, I will close this. 
But I regularly monitor what happens within the react-native discussion.
