### ISSUE TITLE
Node stack is parsed wrong

### ISSUE THREAD

**Issue by dy** [errwischt/stacktrace-parser#15]
In node we have the following stack:
```
Error
    at Spect.get (C:\projects\spect\src\index.js:161:26)
    at Object.get (C:\projects\spect\src\index.js:43:36)
    at <anonymous>
    at (anonymous function).then (C:\projects\spect\src\index.js:165:33)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5)
    at C:\projects\spect\node_modules\esm\esm.js:1:34535
    at C:\projects\spect\node_modules\esm\esm.js:1:34176
    at process.<anonymous> (C:\projects\spect\node_modules\esm\esm.js:1:34506)
    at Function.<anonymous> (C:\projects\spect\node_modules\esm\esm.js:1:296856)
    at Function.<anonymous> (C:\projects\spect\node_modules\esm\esm.js:1:296555)
```
Parsed as 
```js
[ { file: 'C:\\projects\\spect\\src\\index.js',
    methodName: 'Spect.get',
    arguments: [],
    lineNumber: 160,
    column: 34 },
  { file: 'C:\\projects\\spect\\src\\index.js',
    methodName: 'Object.get',
    arguments: [],
    lineNumber: 43,
    column: 36 },
  { file: 'function).then (C:\\projects\\spect\\src\\index.js',
    methodName: '(anonymous',
    arguments: [],
    lineNumber: 165,
    column: 33 },
  { file: 'internal/process/task_queues.js',
    methodName: 'process.runNextTicks [as _tickCallback]',
    arguments: [],
    lineNumber: 52,
    column: 5 },
  { file: 'C:\\projects\\spect\\node_modules\\esm\\esm.js',
    methodName: '<unknown>',
    arguments: [],
    lineNumber: 1,
    column: 34535 },
  { file: 'C:\\projects\\spect\\node_modules\\esm\\esm.js',
    methodName: '<unknown>',
    arguments: [],
    lineNumber: 1,
    column: 34176 },
  { file: 'C:\\projects\\spect\\node_modules\\esm\\esm.js',
    methodName: 'process.<anonymous>',
    arguments: [],
    lineNumber: 1,
    column: 34506 },
  { file: 'C:\\projects\\spect\\node_modules\\esm\\esm.js',
    methodName: 'Function.<anonymous>',
    arguments: [],
    lineNumber: 1,
    column: 296856 },
  { file: 'C:\\projects\\spect\\node_modules\\esm\\esm.js',
    methodName: 'Function.<anonymous>',
    arguments: [],
    lineNumber: 1,
    column: 296555 } ]
```

**Comment by Calamari** [comment]
Thanks for posting this, I'll check why it looks so funky.

**Comment by Calamari** [comment]
It looks like you are running this on a windows machine, with what Node.js version did you run it, @dy?

**Comment by dy** [comment]
That's node v11.14.0

**Comment by Calamari** [comment]
I just pushed a fix. Will deploy a new version soon if nothing out of the ordinary happens. :)

**Comment by dy** [comment]
Thanks for doing that, that's really valuable package

**Comment by Calamari** [comment]
Version is 0.1.7 is out on npm. Have fun with that :)
